site_name: Foguetinho
nav: 
  - Etapa 1 - Fundamentos de Segurança Web e Ferramentas Essenciais: index.md
  - Etapa 2 - Métodos Criptográficos e Ferramentas de Segurança Web: 2.md
  - Etapa 3 - Autenticação com keycloak: 3.md
  - Etapa 4 - Identificação de Controles Relevantes e Implementação de Controles CIS 8: 4.md
theme:
  name: material
  language: pt-BR
  logo: assets/images/icon.svg
  favicon: assets/images/icon.svg
  features:
    - navigation.footer
  palette:
    scheme: slate
    primary: lime
    accent: teal
plugins:
  - mkdocs_quiz
extra:
  generator: false
extra_javascript:
  - assets/javascripts/script.js  
extra_css:
  - assets/stylesheets/style.css
copyright: 'Mensal 2'